name: Secrets Scanning
on:
  push:
    branches: ["*"]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'LICENSE'
  pull_request:
    branches: [main, master]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'LICENSE'
jobs:
  secrets-scan:
    name: Secrets Scan (truffleHog)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run truffleHog OSS
        uses: trufflesecurity/trufflehog@v3.76.3
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
